import {
  faSearch,
  faChevronLeft,
  faChevronRight,
  faRotate,
  faTimes,
  faFilter,
  faGlobe,
  faTv,
  faDna,
  faBookOpen,
  faExpand,
  faLayerGroup,
  faArrowUp,
  faPenToSquare,
  faPlus,
  faTrash,
  faCopy,
  faCheck,
  faArrowLeft,
  faDownload,
  faRotateLeft,
  faHouse,
  faCode,
} from '@fortawesome/free-solid-svg-icons'

export const icons = {
  search: faSearch,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  rotate: faRotate,
  close: faTimes,
  filter: faFilter,
  globe: faGlobe,
  tv: faTv,
  dna: faDna,
  book: faBookOpen,
  expand: faExpand,
  layers: faLayerGroup,
  arrowUp: faArrowUp,
  edit: faPenToSquare,
  plus: faPlus,
  trash: faTrash,
  copy: faCopy,
  check: faCheck,
  arrowLeft: faArrowLeft,
  download: faDownload,
  reset: faRotateLeft,
  home: faHouse,
  code: faCode,
}
